<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <RootNamespace>Ffmpegkit.Ios</RootNamespace>
    <AssemblyName>FFmpegKit.iOS</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="Structs.cs" />
  </ItemGroup>

  <ItemGroup>
    <NativeReference Include="libs\ffmpegkit.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
      <IsCxx>True</IsCxx>
      <Frameworks>AudioToolbox AVFoundation CoreMedia VideoToolbox</Frameworks>
      <LinkerFlags>-lc++ -liconv -lbz2 -lz</LinkerFlags>
    </NativeReference>
    <NativeReference Include="libs\libswscale.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libswresample.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libavutil.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libavformat.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libavfilter.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libavdevice.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
    <NativeReference Include="libs\libavcodec.xcframework">
      <Kind>Framework</Kind>
      <IsCxx>True</IsCxx>
    </NativeReference>
  </ItemGroup>
</Project>
